package bank.management.system;

import javax.swing.JOptionPane;

public class AccountInfo extends javax.swing.JPanel {

    private final DatabaseManager databaseManager;

    /**
     * Creates new form AccountInfo
     */
    public AccountInfo() {
        initComponents();
        databaseManager = new DatabaseManager(); // Initialize the DatabaseManager
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelFatherName = new javax.swing.JLabel();
        jLabelMotherName = new javax.swing.JLabel();
        jLabelPresentAddress = new javax.swing.JLabel();
        jLabelPermanentAddress = new javax.swing.JLabel();
        jLabelDOB = new javax.swing.JLabel();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabelUsername.setText("Username:");

        jLabelFatherName.setText("Father's Name:");

        jLabelMotherName.setText("Mother's Name:");

        jLabelPresentAddress.setText("Present Address:");

        jLabelPermanentAddress.setText("Permanent Address:");

        jLabelDOB.setText("Date of Birth:");

        jLabelPhoneNumber.setText("Phone Number:");

        jLabelEmail.setText("Email:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabelFatherName)
                    .addComponent(jLabelMotherName)
                    .addComponent(jLabelPresentAddress)
                    .addComponent(jLabelPermanentAddress)
                    .addComponent(jLabelDOB)
                    .addComponent(jLabelPhoneNumber)
                    .addComponent(jLabelEmail))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFatherName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMotherName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPresentAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPermanentAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDOB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPhoneNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmail)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    public void accountInfo(String uniqueId) {
        // Call the accountInfo method and display the retrieved data
        AccountInfoData accountInfoData = databaseManager.accountInfo(uniqueId);
        // Update UI components with the retrieved data
        jLabelUsername.setText("Username: " + accountInfoData.getUsername());
        jLabelFatherName.setText("Father's Name: " + accountInfoData.getFatherName());
        jLabelMotherName.setText("Mother's Name: " + accountInfoData.getMotherName());
        jLabelPresentAddress.setText("Present Address: " + accountInfoData.getPresentAddress());
        jLabelPermanentAddress.setText("Permanent Address: " + accountInfoData.getPermanentAddress());
        jLabelDOB.setText("Date of Birth: " + accountInfoData.getDateOfBirth());
        jLabelPhoneNumber.setText("Phone Number: " + accountInfoData.getPhoneNumber());
        jLabelEmail.setText("Email: " + accountInfoData.getEmail());
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabelDOB;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFatherName;
    private javax.swing.JLabel jLabelMotherName;
    private javax.swing.JLabel jLabelPermanentAddress;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelPresentAddress;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   


}
